# Generated by Django 4.1.5 on 2023-01-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
